spring.config.activate.on-profile=dev
server.port=8080
spring.config.activate.on-profile=dev

server.port=8080

spring.jpa.hibernate.ddl-auto=update

weather.api.base-url=https://api.weatherapi.com/v1